# Generated by Django 3.2.8 on 2021-10-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='R_info',
            fields=[
                ('rId', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=100)),
                ('serving', models.CharField(max_length=20)),
                ('cookingTime', models.CharField(max_length=20)),
                ('difficult', models.CharField(max_length=20)),
                ('recipe_source', models.CharField(max_length=100)),
                ('menu_img', models.CharField(max_length=100)),
                ('recipe_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='R_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_order', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('rId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverProject.r_info')),
            ],
        ),
        migrations.CreateModel(
            name='R_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('grade', models.IntegerField()),
                ('rId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverProject.r_info')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverProject.user')),
            ],
        ),
    ]
