# Generated by Django 3.0.7 on 2021-11-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main_defaultRecipe',
            new_name='MainDefault',
        ),
        migrations.RenameModel(
            old_name='ranking_defaultRecipe',
            new_name='RankingDefault',
        ),
        migrations.AddField(
            model_name='r_grade',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverProject.R_info')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverProject.User')),
            ],
        ),
    ]
