# Generated by Django 3.0.7 on 2021-11-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0004_userrecipelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_info',
            name='rId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
