# Generated by Django 3.0.7 on 2021-11-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0005_auto_20211104_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindefault',
            name='rId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainRecipes', to='serverProject.R_info'),
        ),
        migrations.AlterField(
            model_name='rankingdefault',
            name='rId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankingRecipes', to='serverProject.R_info'),
        ),
        migrations.AlterField(
            model_name='userrecipelist',
            name='rId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRecipes', to='serverProject.R_info'),
        ),
        migrations.AlterField(
            model_name='userrecipelist',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRecipes', to='serverProject.User'),
        ),
    ]
