# Generated by Django 3.0.7 on 2021-11-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0006_auto_20211104_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipelist',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='serverProject.User'),
        ),
    ]
