# Generated by Django 3.0.7 on 2021-11-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0007_auto_20211104_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_info',
            name='recipe_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='r_order',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserPreferredCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersInCategory', to='serverProject.User')),
            ],
        ),
    ]
