# Generated by Django 3.0 on 2021-11-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0009_rankingviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RankingDefault',
        ),
    ]
