# Generated by Django 3.0 on 2021-11-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0010_delete_rankingdefault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r_info',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='r_info',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='r_order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='r_order',
            name='updated_at',
        ),
    ]
