# Generated by Django 3.0 on 2021-11-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0012_tenthousand_r_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_order',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
