# Generated by Django 3.0 on 2021-11-15 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0013_auto_20211115_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferredCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersInCategory', to='serverProject.User')),
            ],
        ),
    ]
