# Generated by Django 3.0 on 2021-11-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0014_userpreferredcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_info',
            name='recipe_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
