# Generated by Django 3.0 on 2021-11-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverProject', '0015_r_info_recipe_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunnyRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunnyRecipes', to='serverProject.R_info')),
            ],
        ),
        migrations.CreateModel(
            name='SnowyRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snowyRecipes', to='serverProject.R_info')),
            ],
        ),
        migrations.CreateModel(
            name='RainyRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainyRecipes', to='serverProject.R_info')),
            ],
        ),
        migrations.CreateModel(
            name='CloudyRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudyRecipes', to='serverProject.R_info')),
            ],
        ),
    ]
